from database import engine, SessionLocal, Base
from models import Food, Meal

Base.metadata.create_all(bind=engine)


def seed():
    db = SessionLocal()

    if db.query(Food).count() > 0:
        print("Database already seeded. Skipping.")
        db.close()
        return

    foods = [
        # ── VEG ─────────────────────────────────────────────────
        Food(name="Spinach (Palak)", category="vegetable", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=2.7, calcium_mg=99, folic_acid_mcg=194, protein_g=2.9),
        Food(name="Paneer", category="dairy", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.2, calcium_mg=208, folic_acid_mcg=15, protein_g=18.3),
        Food(name="Dal (Moong)", category="grain", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=3.0, calcium_mg=27, folic_acid_mcg=159, protein_g=24.0),
        Food(name="Dal (Masoor)", category="grain", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=3.3, calcium_mg=19, folic_acid_mcg=181, protein_g=25.8),
        Food(name="Curd (Dahi)", category="dairy", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.1, calcium_mg=110, folic_acid_mcg=7, protein_g=3.5),
        Food(name="Milk", category="dairy", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.1, calcium_mg=125, folic_acid_mcg=5, protein_g=3.4),
        Food(name="Banana", category="fruit", diet_type="veg", safety="safe",
             trimester_best="1", iron_mg=0.3, calcium_mg=5, folic_acid_mcg=20, protein_g=1.1),
        Food(name="Pomegranate", category="fruit", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.3, calcium_mg=10, folic_acid_mcg=38, protein_g=1.7),
        Food(name="Sweet Potato", category="vegetable", diet_type="veg", safety="safe",
             trimester_best="1", iron_mg=0.6, calcium_mg=30, folic_acid_mcg=11, protein_g=1.6),
        Food(name="Beetroot", category="vegetable", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.8, calcium_mg=16, folic_acid_mcg=109, protein_g=1.6),
        Food(name="Broccoli", category="vegetable", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.7, calcium_mg=47, folic_acid_mcg=63, protein_g=2.8),
        Food(name="Carrot", category="vegetable", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.3, calcium_mg=33, folic_acid_mcg=19, protein_g=0.9),
        Food(name="Roti (Wheat)", category="grain", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=2.5, calcium_mg=30, folic_acid_mcg=28, protein_g=11.0),
        Food(name="Rice (White)", category="grain", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.8, calcium_mg=10, folic_acid_mcg=8, protein_g=2.7),
        Food(name="Oats", category="grain", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=4.7, calcium_mg=54, folic_acid_mcg=56, protein_g=16.9),
        Food(name="Mango", category="fruit", diet_type="veg", safety="safe",
             trimester_best="2", iron_mg=0.2, calcium_mg=11, folic_acid_mcg=43, protein_g=0.8),
        Food(name="Apple", category="fruit", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.1, calcium_mg=6, folic_acid_mcg=3, protein_g=0.3),
        Food(name="Orange", category="fruit", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.1, calcium_mg=40, folic_acid_mcg=30, protein_g=0.9),
        Food(name="Ghee", category="dairy", diet_type="veg", safety="moderation",
             safety_reason="High in saturated fat, limit to 1-2 tsp per day",
             trimester_best="all", iron_mg=0.0, calcium_mg=0, folic_acid_mcg=0, protein_g=0.0),
        Food(name="Potato", category="vegetable", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.8, calcium_mg=12, folic_acid_mcg=15, protein_g=2.0),
        Food(name="Rajma (Kidney Beans)", category="grain", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=2.9, calcium_mg=43, folic_acid_mcg=130, protein_g=8.7),
        Food(name="Chana (Chickpeas)", category="grain", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=2.9, calcium_mg=49, folic_acid_mcg=172, protein_g=8.9),
        Food(name="Dry Dates (Khajur)", category="fruit", diet_type="veg", safety="safe",
             trimester_best="3", iron_mg=1.0, calcium_mg=64, folic_acid_mcg=15, protein_g=2.5),
        Food(name="Coconut Water", category="beverage", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.3, calcium_mg=24, folic_acid_mcg=3, protein_g=0.7),
        Food(name="Buttermilk (Chaas)", category="beverage", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.0, calcium_mg=116, folic_acid_mcg=5, protein_g=3.3),
        Food(name="Amla (Indian Gooseberry)", category="fruit", diet_type="veg", safety="safe",
             trimester_best="all", iron_mg=0.3, calcium_mg=25, folic_acid_mcg=6, protein_g=0.9),

        # ── NON-VEG ─────────────────────────────────────────────
        Food(name="Chicken Breast", category="meat", diet_type="non-veg", safety="safe",
             safety_reason="Must be fully cooked",
             trimester_best="all", iron_mg=0.7, calcium_mg=11, folic_acid_mcg=4, protein_g=31.0),
        Food(name="Mutton (Goat)", category="meat", diet_type="non-veg", safety="safe",
             safety_reason="Must be fully cooked",
             trimester_best="all", iron_mg=2.8, calcium_mg=13, folic_acid_mcg=5, protein_g=27.0),
        Food(name="Salmon", category="seafood", diet_type="non-veg", safety="safe",
             trimester_best="all", iron_mg=0.3, calcium_mg=9, folic_acid_mcg=7, protein_g=20.0),
        Food(name="Sardine", category="seafood", diet_type="non-veg", safety="safe",
             trimester_best="all", iron_mg=2.9, calcium_mg=382, folic_acid_mcg=10, protein_g=25.0),
        Food(name="Prawns", category="seafood", diet_type="non-veg", safety="moderation",
             safety_reason="Limit to 2-3 servings per week, ensure fully cooked",
             trimester_best="all", iron_mg=0.5, calcium_mg=70, folic_acid_mcg=3, protein_g=24.0),
        Food(name="Chicken Liver", category="meat", diet_type="non-veg", safety="moderation",
             safety_reason="Very high in Vitamin A, excess can harm baby. Limit to once a week",
             trimester_best="2", iron_mg=9.0, calcium_mg=5, folic_acid_mcg=560, protein_g=26.0),
        Food(name="Fish Curry (Rohu)", category="seafood", diet_type="non-veg", safety="safe",
             safety_reason="Must be fully cooked",
             trimester_best="all", iron_mg=0.6, calcium_mg=40, folic_acid_mcg=8, protein_g=17.0),

        # ── EGG ─────────────────────────────────────────────────
        Food(name="Boiled Egg", category="egg", diet_type="egg", safety="safe",
             safety_reason="Must be fully cooked, avoid runny yolk",
             trimester_best="all", iron_mg=1.2, calcium_mg=50, folic_acid_mcg=44, protein_g=13.0),
        Food(name="Egg Omelette", category="egg", diet_type="egg", safety="safe",
             safety_reason="Must be fully cooked",
             trimester_best="all", iron_mg=1.5, calcium_mg=48, folic_acid_mcg=40, protein_g=11.0),
        Food(name="Egg Curry", category="egg", diet_type="egg", safety="safe",
             safety_reason="Must be fully cooked",
             trimester_best="all", iron_mg=1.8, calcium_mg=55, folic_acid_mcg=42, protein_g=12.0),
        Food(name="Egg Bhurji", category="egg", diet_type="egg", safety="safe",
             safety_reason="Must be fully cooked",
             trimester_best="all", iron_mg=1.4, calcium_mg=45, folic_acid_mcg=38, protein_g=10.5),

        # ── VEGAN ───────────────────────────────────────────────
        Food(name="Tofu", category="dairy", diet_type="vegan", safety="safe",
             trimester_best="all", iron_mg=5.4, calcium_mg=350, folic_acid_mcg=15, protein_g=8.0),
        Food(name="Soy Milk", category="beverage", diet_type="vegan", safety="safe",
             trimester_best="all", iron_mg=0.6, calcium_mg=25, folic_acid_mcg=18, protein_g=3.3),
        Food(name="Quinoa", category="grain", diet_type="vegan", safety="safe",
             trimester_best="all", iron_mg=1.5, calcium_mg=17, folic_acid_mcg=42, protein_g=4.4),
        Food(name="Chia Seeds", category="nuts", diet_type="vegan", safety="safe",
             trimester_best="all", iron_mg=7.7, calcium_mg=631, folic_acid_mcg=49, protein_g=17.0),
        Food(name="Almonds (Badam)", category="nuts", diet_type="vegan", safety="safe",
             trimester_best="all", iron_mg=3.7, calcium_mg=264, folic_acid_mcg=44, protein_g=21.2),
        Food(name="Walnuts (Akhrot)", category="nuts", diet_type="vegan", safety="safe",
             trimester_best="all", iron_mg=2.9, calcium_mg=98, folic_acid_mcg=98, protein_g=15.2),
        Food(name="Flax Seeds (Alsi)", category="nuts", diet_type="vegan", safety="moderation",
             safety_reason="Contains phytoestrogens, limit to 1 tbsp per day",
             trimester_best="all", iron_mg=5.7, calcium_mg=255, folic_acid_mcg=87, protein_g=18.3),
        Food(name="Peanuts (Moongfali)", category="nuts", diet_type="vegan", safety="safe",
             trimester_best="all", iron_mg=4.6, calcium_mg=92, folic_acid_mcg=240, protein_g=25.8),
        Food(name="Sesame Seeds (Til)", category="nuts", diet_type="vegan", safety="safe",
             trimester_best="all", iron_mg=14.6, calcium_mg=975, folic_acid_mcg=97, protein_g=17.7),
        Food(name="Ragi (Finger Millet)", category="grain", diet_type="vegan", safety="safe",
             trimester_best="all", iron_mg=3.9, calcium_mg=344, folic_acid_mcg=18, protein_g=7.3),

        # ── UNSAFE / AVOID ──────────────────────────────────────
        Food(name="Raw Papaya", category="fruit", diet_type="veg", safety="unsafe",
             safety_reason="Contains papain enzyme that can cause uterine contractions and early labour",
             trimester_best="all", iron_mg=0.3, calcium_mg=20, folic_acid_mcg=37, protein_g=0.5),
        Food(name="Pineapple", category="fruit", diet_type="veg", safety="moderation",
             safety_reason="Contains bromelain which may soften cervix. Small amounts are okay, avoid in first trimester",
             trimester_best="2", iron_mg=0.3, calcium_mg=13, folic_acid_mcg=18, protein_g=0.5),
        Food(name="Raw/Sushi Fish", category="seafood", diet_type="non-veg", safety="unsafe",
             safety_reason="Risk of listeria, salmonella, and parasites. Always eat fully cooked fish",
             trimester_best="all", iron_mg=0.5, calcium_mg=10, folic_acid_mcg=5, protein_g=20.0),
        Food(name="Soft Cheese (Brie/Camembert)", category="dairy", diet_type="veg", safety="unsafe",
             safety_reason="Unpasteurised soft cheese can contain listeria bacteria harmful to baby",
             trimester_best="all", iron_mg=0.2, calcium_mg=184, folic_acid_mcg=18, protein_g=17.0),
        Food(name="Coffee", category="beverage", diet_type="veg", safety="moderation",
             safety_reason="Limit caffeine to 200mg per day (about 1 cup). Excess linked to low birth weight",
             trimester_best="all", iron_mg=0.0, calcium_mg=2, folic_acid_mcg=0, protein_g=0.0),
        Food(name="Tea (Chai)", category="beverage", diet_type="veg", safety="moderation",
             safety_reason="Contains caffeine and tannins which reduce iron absorption. Limit to 1-2 cups",
             trimester_best="all", iron_mg=0.0, calcium_mg=0, folic_acid_mcg=0, protein_g=0.0),
        Food(name="Alcohol", category="beverage", diet_type="veg", safety="unsafe",
             safety_reason="No safe amount during pregnancy. Can cause fetal alcohol syndrome",
             trimester_best="all", iron_mg=0.0, calcium_mg=0, folic_acid_mcg=0, protein_g=0.0),
        Food(name="Ajinomoto (MSG)", category="other", diet_type="veg", safety="unsafe",
             safety_reason="May cross placenta and affect fetal brain development. Avoid Chinese food with MSG",
             trimester_best="all", iron_mg=0.0, calcium_mg=0, folic_acid_mcg=0, protein_g=0.0),
        Food(name="Raw Sprouts", category="vegetable", diet_type="veg", safety="unsafe",
             safety_reason="Raw sprouts may harbour salmonella and E.coli. Always cook sprouts thoroughly",
             trimester_best="all", iron_mg=0.9, calcium_mg=13, folic_acid_mcg=60, protein_g=3.0),
    ]

    meals = [
        # ── VEG MEALS ───────────────────────────────────────────
        Meal(name="Oats with Milk & Banana", meal_type="breakfast", diet_type="veg", trimester="1",
             description="Easy on stomach, great for morning sickness",
             ingredients="Oats, milk, banana, honey, cardamom"),
        Meal(name="Poha with Peanuts", meal_type="breakfast", diet_type="veg", trimester="all",
             description="Light, iron-rich breakfast",
             ingredients="Flattened rice, peanuts, curry leaves, turmeric, lemon"),
        Meal(name="Ragi Dosa with Chutney", meal_type="breakfast", diet_type="veg", trimester="all",
             description="Calcium-rich traditional breakfast",
             ingredients="Ragi flour, rice flour, coconut chutney"),
        Meal(name="Paneer Paratha with Curd", meal_type="breakfast", diet_type="veg", trimester="2",
             description="Protein and calcium packed",
             ingredients="Wheat flour, paneer, curd, spices"),
        Meal(name="Palak Dal with Rice", meal_type="lunch", diet_type="veg", trimester="all",
             description="Iron and folic acid rich complete meal",
             ingredients="Spinach, moong dal, rice, ghee, cumin"),
        Meal(name="Rajma Chawal", meal_type="lunch", diet_type="veg", trimester="all",
             description="Protein-rich comfort food",
             ingredients="Kidney beans, rice, onion, tomato, spices"),
        Meal(name="Chole with Roti", meal_type="lunch", diet_type="veg", trimester="2",
             description="High protein and iron",
             ingredients="Chickpeas, wheat roti, onion, spices"),
        Meal(name="Vegetable Khichdi", meal_type="lunch", diet_type="veg", trimester="1",
             description="Easy to digest, good during nausea",
             ingredients="Rice, moong dal, mixed vegetables, ghee"),
        Meal(name="Beetroot Raita", meal_type="snack", diet_type="veg", trimester="all",
             description="Iron and calcium booster",
             ingredients="Beetroot, curd, cumin, salt"),
        Meal(name="Dry Fruit Laddoo", meal_type="snack", diet_type="veg", trimester="3",
             description="Energy booster for third trimester",
             ingredients="Dates, almonds, walnuts, coconut, ghee"),
        Meal(name="Fruit Chaat", meal_type="snack", diet_type="veg", trimester="all",
             description="Vitamin C rich refreshing snack",
             ingredients="Pomegranate, apple, banana, orange, chaat masala"),
        Meal(name="Paneer Butter Masala with Roti", meal_type="dinner", diet_type="veg", trimester="2",
             description="Protein-rich satisfying dinner",
             ingredients="Paneer, butter, tomato, cream, wheat roti"),
        Meal(name="Dal Tadka with Roti", meal_type="dinner", diet_type="veg", trimester="all",
             description="Light yet nutritious dinner",
             ingredients="Masoor dal, ghee, cumin, garlic, roti"),
        Meal(name="Mixed Veg Curry with Rice", meal_type="dinner", diet_type="veg", trimester="all",
             description="Balanced meal with multiple nutrients",
             ingredients="Carrot, beans, potato, peas, rice"),

        # ── NON-VEG MEALS ───────────────────────────────────────
        Meal(name="Chicken Sandwich", meal_type="breakfast", diet_type="non-veg", trimester="all",
             description="Protein-packed start to the day",
             ingredients="Whole wheat bread, chicken breast, lettuce, tomato"),
        Meal(name="Chicken Curry with Rice", meal_type="lunch", diet_type="non-veg", trimester="all",
             description="High protein complete meal",
             ingredients="Chicken, rice, onion, tomato, ginger, spices"),
        Meal(name="Mutton Keema with Roti", meal_type="lunch", diet_type="non-veg", trimester="2",
             description="Iron-rich meal for preventing anaemia",
             ingredients="Minced mutton, wheat roti, peas, spices"),
        Meal(name="Fish Curry with Rice", meal_type="lunch", diet_type="non-veg", trimester="all",
             description="Omega-3 rich brain food for baby",
             ingredients="Rohu fish, rice, mustard, turmeric, coconut"),
        Meal(name="Chicken Soup", meal_type="snack", diet_type="non-veg", trimester="1",
             description="Soothing during morning sickness",
             ingredients="Chicken, carrots, celery, garlic, ginger"),
        Meal(name="Grilled Salmon with Vegetables", meal_type="dinner", diet_type="non-veg", trimester="all",
             description="Omega-3 and DHA for baby brain development",
             ingredients="Salmon, broccoli, lemon, olive oil"),
        Meal(name="Chicken Biryani", meal_type="dinner", diet_type="non-veg", trimester="2",
             description="Flavourful protein meal (limit spice)",
             ingredients="Chicken, basmati rice, yogurt, saffron, spices"),

        # ── EGG MEALS ───────────────────────────────────────────
        Meal(name="Boiled Egg with Toast", meal_type="breakfast", diet_type="egg", trimester="all",
             description="Quick protein breakfast",
             ingredients="Eggs, whole wheat bread, butter"),
        Meal(name="Egg Omelette with Vegetables", meal_type="breakfast", diet_type="egg", trimester="all",
             description="Protein and folate rich start",
             ingredients="Eggs, onion, tomato, capsicum, spinach"),
        Meal(name="Egg Fried Rice", meal_type="lunch", diet_type="egg", trimester="all",
             description="Quick and filling meal",
             ingredients="Rice, eggs, vegetables, soy sauce, garlic"),
        Meal(name="Egg Curry with Roti", meal_type="dinner", diet_type="egg", trimester="all",
             description="Protein-rich Indian dinner",
             ingredients="Eggs, onion, tomato, spices, roti"),
        Meal(name="Egg Bhurji with Paratha", meal_type="dinner", diet_type="egg", trimester="2",
             description="Scrambled egg with Indian spices",
             ingredients="Eggs, onion, green chilli, coriander, paratha"),

        # ── VEGAN MEALS ─────────────────────────────────────────
        Meal(name="Quinoa Porridge with Nuts", meal_type="breakfast", diet_type="vegan", trimester="all",
             description="Complete protein breakfast",
             ingredients="Quinoa, almond milk, almonds, walnuts, honey"),
        Meal(name="Ragi Porridge with Jaggery", meal_type="breakfast", diet_type="vegan", trimester="all",
             description="Calcium powerhouse",
             ingredients="Ragi flour, jaggery, cardamom, soy milk"),
        Meal(name="Tofu Stir Fry with Rice", meal_type="lunch", diet_type="vegan", trimester="all",
             description="High protein plant-based meal",
             ingredients="Tofu, bell peppers, broccoli, soy sauce, rice"),
        Meal(name="Chana Masala with Quinoa", meal_type="lunch", diet_type="vegan", trimester="all",
             description="Iron and protein rich",
             ingredients="Chickpeas, quinoa, tomato, onion, spices"),
        Meal(name="Trail Mix", meal_type="snack", diet_type="vegan", trimester="all",
             description="Energy and nutrient dense snack",
             ingredients="Almonds, walnuts, pumpkin seeds, dried cranberries"),
        Meal(name="Peanut Butter Banana Smoothie", meal_type="snack", diet_type="vegan", trimester="all",
             description="Protein and potassium boost",
             ingredients="Banana, peanut butter, soy milk, chia seeds"),
        Meal(name="Dal with Ragi Roti", meal_type="dinner", diet_type="vegan", trimester="all",
             description="Iron + calcium combo dinner",
             ingredients="Masoor dal, ragi flour roti, garlic, cumin"),
        Meal(name="Mushroom Curry with Rice", meal_type="dinner", diet_type="vegan", trimester="2",
             description="B-vitamin rich comforting meal",
             ingredients="Mushrooms, coconut milk, rice, spices"),
    ]

    db.add_all(foods)
    db.add_all(meals)
    db.commit()
    db.close()
    print(f"Seeded {len(foods)} foods and {len(meals)} meals successfully!")


if __name__ == "__main__":
    seed()
