export const DAILY_RECOMMENDED = {
  iron_mg: 27.0,
  calcium_mg: 1000.0,
  folic_acid_mcg: 600.0,
  protein_g: 71.0,
}

export const FOODS = [
  {id:1,name:"Spinach (Palak)",category:"vegetable",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:2.7,calcium_mg:99,folic_acid_mcg:194,protein_g:2.9},
  {id:2,name:"Paneer",category:"dairy",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.2,calcium_mg:208,folic_acid_mcg:15,protein_g:18.3},
  {id:3,name:"Dal (Moong)",category:"grain",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:3.0,calcium_mg:27,folic_acid_mcg:159,protein_g:24.0},
  {id:4,name:"Dal (Masoor)",category:"grain",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:3.3,calcium_mg:19,folic_acid_mcg:181,protein_g:25.8},
  {id:5,name:"Curd (Dahi)",category:"dairy",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.1,calcium_mg:110,folic_acid_mcg:7,protein_g:3.5},
  {id:6,name:"Milk",category:"dairy",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.1,calcium_mg:125,folic_acid_mcg:5,protein_g:3.4},
  {id:7,name:"Banana",category:"fruit",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"1",iron_mg:0.3,calcium_mg:5,folic_acid_mcg:20,protein_g:1.1},
  {id:8,name:"Pomegranate",category:"fruit",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.3,calcium_mg:10,folic_acid_mcg:38,protein_g:1.7},
  {id:9,name:"Sweet Potato",category:"vegetable",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"1",iron_mg:0.6,calcium_mg:30,folic_acid_mcg:11,protein_g:1.6},
  {id:10,name:"Beetroot",category:"vegetable",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.8,calcium_mg:16,folic_acid_mcg:109,protein_g:1.6},
  {id:11,name:"Broccoli",category:"vegetable",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.7,calcium_mg:47,folic_acid_mcg:63,protein_g:2.8},
  {id:12,name:"Carrot",category:"vegetable",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.3,calcium_mg:33,folic_acid_mcg:19,protein_g:0.9},
  {id:13,name:"Roti (Wheat)",category:"grain",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:2.5,calcium_mg:30,folic_acid_mcg:28,protein_g:11.0},
  {id:14,name:"Rice (White)",category:"grain",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.8,calcium_mg:10,folic_acid_mcg:8,protein_g:2.7},
  {id:15,name:"Oats",category:"grain",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:4.7,calcium_mg:54,folic_acid_mcg:56,protein_g:16.9},
  {id:16,name:"Mango",category:"fruit",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"2",iron_mg:0.2,calcium_mg:11,folic_acid_mcg:43,protein_g:0.8},
  {id:17,name:"Apple",category:"fruit",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.1,calcium_mg:6,folic_acid_mcg:3,protein_g:0.3},
  {id:18,name:"Orange",category:"fruit",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.1,calcium_mg:40,folic_acid_mcg:30,protein_g:0.9},
  {id:19,name:"Ghee",category:"dairy",diet_type:"veg",safety:"moderation",safety_reason:"High in saturated fat, limit to 1-2 tsp per day",trimester_best:"all",iron_mg:0.0,calcium_mg:0,folic_acid_mcg:0,protein_g:0.0},
  {id:20,name:"Potato",category:"vegetable",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.8,calcium_mg:12,folic_acid_mcg:15,protein_g:2.0},
  {id:21,name:"Rajma (Kidney Beans)",category:"grain",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:2.9,calcium_mg:43,folic_acid_mcg:130,protein_g:8.7},
  {id:22,name:"Chana (Chickpeas)",category:"grain",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:2.9,calcium_mg:49,folic_acid_mcg:172,protein_g:8.9},
  {id:23,name:"Dry Dates (Khajur)",category:"fruit",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"3",iron_mg:1.0,calcium_mg:64,folic_acid_mcg:15,protein_g:2.5},
  {id:24,name:"Coconut Water",category:"beverage",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.3,calcium_mg:24,folic_acid_mcg:3,protein_g:0.7},
  {id:25,name:"Buttermilk (Chaas)",category:"beverage",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.0,calcium_mg:116,folic_acid_mcg:5,protein_g:3.3},
  {id:26,name:"Amla (Indian Gooseberry)",category:"fruit",diet_type:"veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.3,calcium_mg:25,folic_acid_mcg:6,protein_g:0.9},
  {id:27,name:"Chicken Breast",category:"meat",diet_type:"non-veg",safety:"safe",safety_reason:"Must be fully cooked",trimester_best:"all",iron_mg:0.7,calcium_mg:11,folic_acid_mcg:4,protein_g:31.0},
  {id:28,name:"Mutton (Goat)",category:"meat",diet_type:"non-veg",safety:"safe",safety_reason:"Must be fully cooked",trimester_best:"all",iron_mg:2.8,calcium_mg:13,folic_acid_mcg:5,protein_g:27.0},
  {id:29,name:"Salmon",category:"seafood",diet_type:"non-veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.3,calcium_mg:9,folic_acid_mcg:7,protein_g:20.0},
  {id:30,name:"Sardine",category:"seafood",diet_type:"non-veg",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:2.9,calcium_mg:382,folic_acid_mcg:10,protein_g:25.0},
  {id:31,name:"Prawns",category:"seafood",diet_type:"non-veg",safety:"moderation",safety_reason:"Limit to 2-3 servings per week, ensure fully cooked",trimester_best:"all",iron_mg:0.5,calcium_mg:70,folic_acid_mcg:3,protein_g:24.0},
  {id:32,name:"Chicken Liver",category:"meat",diet_type:"non-veg",safety:"moderation",safety_reason:"Very high in Vitamin A, excess can harm baby. Limit to once a week",trimester_best:"2",iron_mg:9.0,calcium_mg:5,folic_acid_mcg:560,protein_g:26.0},
  {id:33,name:"Fish Curry (Rohu)",category:"seafood",diet_type:"non-veg",safety:"safe",safety_reason:"Must be fully cooked",trimester_best:"all",iron_mg:0.6,calcium_mg:40,folic_acid_mcg:8,protein_g:17.0},
  {id:34,name:"Boiled Egg",category:"egg",diet_type:"egg",safety:"safe",safety_reason:"Must be fully cooked, avoid runny yolk",trimester_best:"all",iron_mg:1.2,calcium_mg:50,folic_acid_mcg:44,protein_g:13.0},
  {id:35,name:"Egg Omelette",category:"egg",diet_type:"egg",safety:"safe",safety_reason:"Must be fully cooked",trimester_best:"all",iron_mg:1.5,calcium_mg:48,folic_acid_mcg:40,protein_g:11.0},
  {id:36,name:"Egg Curry",category:"egg",diet_type:"egg",safety:"safe",safety_reason:"Must be fully cooked",trimester_best:"all",iron_mg:1.8,calcium_mg:55,folic_acid_mcg:42,protein_g:12.0},
  {id:37,name:"Egg Bhurji",category:"egg",diet_type:"egg",safety:"safe",safety_reason:"Must be fully cooked",trimester_best:"all",iron_mg:1.4,calcium_mg:45,folic_acid_mcg:38,protein_g:10.5},
  {id:38,name:"Tofu",category:"dairy",diet_type:"vegan",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:5.4,calcium_mg:350,folic_acid_mcg:15,protein_g:8.0},
  {id:39,name:"Soy Milk",category:"beverage",diet_type:"vegan",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:0.6,calcium_mg:25,folic_acid_mcg:18,protein_g:3.3},
  {id:40,name:"Quinoa",category:"grain",diet_type:"vegan",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:1.5,calcium_mg:17,folic_acid_mcg:42,protein_g:4.4},
  {id:41,name:"Chia Seeds",category:"nuts",diet_type:"vegan",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:7.7,calcium_mg:631,folic_acid_mcg:49,protein_g:17.0},
  {id:42,name:"Almonds (Badam)",category:"nuts",diet_type:"vegan",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:3.7,calcium_mg:264,folic_acid_mcg:44,protein_g:21.2},
  {id:43,name:"Walnuts (Akhrot)",category:"nuts",diet_type:"vegan",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:2.9,calcium_mg:98,folic_acid_mcg:98,protein_g:15.2},
  {id:44,name:"Flax Seeds (Alsi)",category:"nuts",diet_type:"vegan",safety:"moderation",safety_reason:"Contains phytoestrogens, limit to 1 tbsp per day",trimester_best:"all",iron_mg:5.7,calcium_mg:255,folic_acid_mcg:87,protein_g:18.3},
  {id:45,name:"Peanuts (Moongfali)",category:"nuts",diet_type:"vegan",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:4.6,calcium_mg:92,folic_acid_mcg:240,protein_g:25.8},
  {id:46,name:"Sesame Seeds (Til)",category:"nuts",diet_type:"vegan",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:14.6,calcium_mg:975,folic_acid_mcg:97,protein_g:17.7},
  {id:47,name:"Ragi (Finger Millet)",category:"grain",diet_type:"vegan",safety:"safe",safety_reason:null,trimester_best:"all",iron_mg:3.9,calcium_mg:344,folic_acid_mcg:18,protein_g:7.3},
  {id:48,name:"Raw Papaya",category:"fruit",diet_type:"veg",safety:"unsafe",safety_reason:"Contains papain enzyme that can cause uterine contractions and early labour",trimester_best:"all",iron_mg:0.3,calcium_mg:20,folic_acid_mcg:37,protein_g:0.5},
  {id:49,name:"Pineapple",category:"fruit",diet_type:"veg",safety:"moderation",safety_reason:"Contains bromelain which may soften cervix. Small amounts are okay, avoid in first trimester",trimester_best:"2",iron_mg:0.3,calcium_mg:13,folic_acid_mcg:18,protein_g:0.5},
  {id:50,name:"Raw/Sushi Fish",category:"seafood",diet_type:"non-veg",safety:"unsafe",safety_reason:"Risk of listeria, salmonella, and parasites. Always eat fully cooked fish",trimester_best:"all",iron_mg:0.5,calcium_mg:10,folic_acid_mcg:5,protein_g:20.0},
  {id:51,name:"Soft Cheese (Brie/Camembert)",category:"dairy",diet_type:"veg",safety:"unsafe",safety_reason:"Unpasteurised soft cheese can contain listeria bacteria harmful to baby",trimester_best:"all",iron_mg:0.2,calcium_mg:184,folic_acid_mcg:18,protein_g:17.0},
  {id:52,name:"Coffee",category:"beverage",diet_type:"veg",safety:"moderation",safety_reason:"Limit caffeine to 200mg per day (about 1 cup). Excess linked to low birth weight",trimester_best:"all",iron_mg:0.0,calcium_mg:2,folic_acid_mcg:0,protein_g:0.0},
  {id:53,name:"Tea (Chai)",category:"beverage",diet_type:"veg",safety:"moderation",safety_reason:"Contains caffeine and tannins which reduce iron absorption. Limit to 1-2 cups",trimester_best:"all",iron_mg:0.0,calcium_mg:0,folic_acid_mcg:0,protein_g:0.0},
  {id:54,name:"Alcohol",category:"beverage",diet_type:"veg",safety:"unsafe",safety_reason:"No safe amount during pregnancy. Can cause fetal alcohol syndrome",trimester_best:"all",iron_mg:0.0,calcium_mg:0,folic_acid_mcg:0,protein_g:0.0},
  {id:55,name:"Ajinomoto (MSG)",category:"other",diet_type:"veg",safety:"unsafe",safety_reason:"May cross placenta and affect fetal brain development. Avoid Chinese food with MSG",trimester_best:"all",iron_mg:0.0,calcium_mg:0,folic_acid_mcg:0,protein_g:0.0},
  {id:56,name:"Raw Sprouts",category:"vegetable",diet_type:"veg",safety:"unsafe",safety_reason:"Raw sprouts may harbour salmonella and E.coli. Always cook sprouts thoroughly",trimester_best:"all",iron_mg:0.9,calcium_mg:13,folic_acid_mcg:60,protein_g:3.0},
]

export const MEALS = [
  {id:1,name:"Oats with Milk & Banana",meal_type:"breakfast",diet_type:"veg",trimester:"1",description:"Easy on stomach, great for morning sickness",ingredients:"Oats, milk, banana, honey, cardamom"},
  {id:2,name:"Poha with Peanuts",meal_type:"breakfast",diet_type:"veg",trimester:"all",description:"Light, iron-rich breakfast",ingredients:"Flattened rice, peanuts, curry leaves, turmeric, lemon"},
  {id:3,name:"Ragi Dosa with Chutney",meal_type:"breakfast",diet_type:"veg",trimester:"all",description:"Calcium-rich traditional breakfast",ingredients:"Ragi flour, rice flour, coconut chutney"},
  {id:4,name:"Paneer Paratha with Curd",meal_type:"breakfast",diet_type:"veg",trimester:"2",description:"Protein and calcium packed",ingredients:"Wheat flour, paneer, curd, spices"},
  {id:5,name:"Palak Dal with Rice",meal_type:"lunch",diet_type:"veg",trimester:"all",description:"Iron and folic acid rich complete meal",ingredients:"Spinach, moong dal, rice, ghee, cumin"},
  {id:6,name:"Rajma Chawal",meal_type:"lunch",diet_type:"veg",trimester:"all",description:"Protein-rich comfort food",ingredients:"Kidney beans, rice, onion, tomato, spices"},
  {id:7,name:"Chole with Roti",meal_type:"lunch",diet_type:"veg",trimester:"2",description:"High protein and iron",ingredients:"Chickpeas, wheat roti, onion, spices"},
  {id:8,name:"Vegetable Khichdi",meal_type:"lunch",diet_type:"veg",trimester:"1",description:"Easy to digest, good during nausea",ingredients:"Rice, moong dal, mixed vegetables, ghee"},
  {id:9,name:"Beetroot Raita",meal_type:"snack",diet_type:"veg",trimester:"all",description:"Iron and calcium booster",ingredients:"Beetroot, curd, cumin, salt"},
  {id:10,name:"Dry Fruit Laddoo",meal_type:"snack",diet_type:"veg",trimester:"3",description:"Energy booster for third trimester",ingredients:"Dates, almonds, walnuts, coconut, ghee"},
  {id:11,name:"Fruit Chaat",meal_type:"snack",diet_type:"veg",trimester:"all",description:"Vitamin C rich refreshing snack",ingredients:"Pomegranate, apple, banana, orange, chaat masala"},
  {id:12,name:"Paneer Butter Masala with Roti",meal_type:"dinner",diet_type:"veg",trimester:"2",description:"Protein-rich satisfying dinner",ingredients:"Paneer, butter, tomato, cream, wheat roti"},
  {id:13,name:"Dal Tadka with Roti",meal_type:"dinner",diet_type:"veg",trimester:"all",description:"Light yet nutritious dinner",ingredients:"Masoor dal, ghee, cumin, garlic, roti"},
  {id:14,name:"Mixed Veg Curry with Rice",meal_type:"dinner",diet_type:"veg",trimester:"all",description:"Balanced meal with multiple nutrients",ingredients:"Carrot, beans, potato, peas, rice"},
  {id:15,name:"Chicken Sandwich",meal_type:"breakfast",diet_type:"non-veg",trimester:"all",description:"Protein-packed start to the day",ingredients:"Whole wheat bread, chicken breast, lettuce, tomato"},
  {id:16,name:"Chicken Curry with Rice",meal_type:"lunch",diet_type:"non-veg",trimester:"all",description:"High protein complete meal",ingredients:"Chicken, rice, onion, tomato, ginger, spices"},
  {id:17,name:"Mutton Keema with Roti",meal_type:"lunch",diet_type:"non-veg",trimester:"2",description:"Iron-rich meal for preventing anaemia",ingredients:"Minced mutton, wheat roti, peas, spices"},
  {id:18,name:"Fish Curry with Rice",meal_type:"lunch",diet_type:"non-veg",trimester:"all",description:"Omega-3 rich brain food for baby",ingredients:"Rohu fish, rice, mustard, turmeric, coconut"},
  {id:19,name:"Chicken Soup",meal_type:"snack",diet_type:"non-veg",trimester:"1",description:"Soothing during morning sickness",ingredients:"Chicken, carrots, celery, garlic, ginger"},
  {id:20,name:"Grilled Salmon with Vegetables",meal_type:"dinner",diet_type:"non-veg",trimester:"all",description:"Omega-3 and DHA for baby brain development",ingredients:"Salmon, broccoli, lemon, olive oil"},
  {id:21,name:"Chicken Biryani",meal_type:"dinner",diet_type:"non-veg",trimester:"2",description:"Flavourful protein meal (limit spice)",ingredients:"Chicken, basmati rice, yogurt, saffron, spices"},
  {id:22,name:"Boiled Egg with Toast",meal_type:"breakfast",diet_type:"egg",trimester:"all",description:"Quick protein breakfast",ingredients:"Eggs, whole wheat bread, butter"},
  {id:23,name:"Egg Omelette with Vegetables",meal_type:"breakfast",diet_type:"egg",trimester:"all",description:"Protein and folate rich start",ingredients:"Eggs, onion, tomato, capsicum, spinach"},
  {id:24,name:"Egg Fried Rice",meal_type:"lunch",diet_type:"egg",trimester:"all",description:"Quick and filling meal",ingredients:"Rice, eggs, vegetables, soy sauce, garlic"},
  {id:25,name:"Egg Curry with Roti",meal_type:"dinner",diet_type:"egg",trimester:"all",description:"Protein-rich Indian dinner",ingredients:"Eggs, onion, tomato, spices, roti"},
  {id:26,name:"Egg Bhurji with Paratha",meal_type:"dinner",diet_type:"egg",trimester:"2",description:"Scrambled egg with Indian spices",ingredients:"Eggs, onion, green chilli, coriander, paratha"},
  {id:27,name:"Quinoa Porridge with Nuts",meal_type:"breakfast",diet_type:"vegan",trimester:"all",description:"Complete protein breakfast",ingredients:"Quinoa, almond milk, almonds, walnuts, honey"},
  {id:28,name:"Ragi Porridge with Jaggery",meal_type:"breakfast",diet_type:"vegan",trimester:"all",description:"Calcium powerhouse",ingredients:"Ragi flour, jaggery, cardamom, soy milk"},
  {id:29,name:"Tofu Stir Fry with Rice",meal_type:"lunch",diet_type:"vegan",trimester:"all",description:"High protein plant-based meal",ingredients:"Tofu, bell peppers, broccoli, soy sauce, rice"},
  {id:30,name:"Chana Masala with Quinoa",meal_type:"lunch",diet_type:"vegan",trimester:"all",description:"Iron and protein rich",ingredients:"Chickpeas, quinoa, tomato, onion, spices"},
  {id:31,name:"Trail Mix",meal_type:"snack",diet_type:"vegan",trimester:"all",description:"Energy and nutrient dense snack",ingredients:"Almonds, walnuts, pumpkin seeds, dried cranberries"},
  {id:32,name:"Peanut Butter Banana Smoothie",meal_type:"snack",diet_type:"vegan",trimester:"all",description:"Protein and potassium boost",ingredients:"Banana, peanut butter, soy milk, chia seeds"},
  {id:33,name:"Dal with Ragi Roti",meal_type:"dinner",diet_type:"vegan",trimester:"all",description:"Iron + calcium combo dinner",ingredients:"Masoor dal, ragi flour roti, garlic, cumin"},
  {id:34,name:"Mushroom Curry with Rice",meal_type:"dinner",diet_type:"vegan",trimester:"2",description:"B-vitamin rich comforting meal",ingredients:"Mushrooms, coconut milk, rice, spices"},
]
